version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/mar1n3r0/app
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -race ./...